### ISSUE TITLE
Deploying API and Lamdba

### ISSUE THREAD

**Issue by LukeDurrant** [dburkland/tesla_cmds_aws_lambda_functions#1]
I started configuring a Zappa Config file so that this can be deployed but struggling with the config.
Can you share details on how you've configured it?

**Comment by LukeDurrant** [comment]
Deployment is in GitHub actions

**Comment by dburkland** [comment]
@LukeDurrant I have the backend AWS infra built out via Terraform, if you want my files for that shoot me a DM on Twitter @dburkland and I can send you a link.

Cheers,

Dan

**Comment by llamafilm** [comment]
@dburkland thank you for sharing, this is great!
I’m going to deploy in my own AWS account because  I don’t like sharing API tokens with anyone. Fortunately none of the iOS actions need to change, only the URL in the config file.

To save myself a dollar a month, I set it up with Lambda Function URL instead of API Gateway. I’m curious if you had some reason to prefer the API Gateway? I’m building a CloudFormation template to share in case other friends want to host their own too.
